### ISSUE TITLE
Path character count limitations

### ISSUE THREAD

**Issue by MilanLund** [Kentico/xperience-by-kentico-kentico-migration-tool#231]
Trying to migrate K13 site. Hotfix v13.0.130. Target is XbyK 29.3.3.

When the migration script finishes and I open the XbyK solution in Visual Studio, it fails to load due to character limitations. Is there an elegant way to resolve this? 

`C:\Users\hello\source\repos\XbyK_TestProject01\XbyK_TestProject01.csproj : error  : Cannot expand metadata in expression "$([MSBuild]::ValueOrDefault('%(FullPath)', '').StartsWith($([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))))". The item metadata "%(FullPath)" cannot be applied to the path "<path>". Path: <path> exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.  C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets`

**Comment by seangwright** [comment]
I think long paths are a more common issue with Xperience by Kentico projects - particularly in the CI and CD repositories because of the long file and folder names.

To fix this issue, enable long path support in Windows with [Git configuration](https://github.com/desktop/desktop/issues/8023#issuecomment-515110259), or [with Group Policy or a registry key change](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#registry-setting-to-enable-long-paths).

**Comment by MilanLund** [comment]
Thank you @seangwright . This has fixed the issue!
