### ISSUE TITLE
Discussion: XbK / Kxp / Target for target identification in config / ns / ...

### ISSUE THREAD

**Issue by tkrch** [Kentico/xperience-by-kentico-kentico-migration-tool#86]

**Comment by phixxo** [comment]
I would like to recommend change some naming conventions and maybe keep the KX vs. XbK to avoid confusion. For example the "TargetCmsDirPath" - since the target is XbK - I would like to suggest "TargetXbKDirPath" it would be better and clearer what is the target and the CMS can invoke the KX13 /CMS folder. The same with "TargetKxpApiSettings" - my suggestion "TargetXbKApiSettings" and in the same manner any other setting if there are still some left.
